#ifndef TENMILMANUI_ENUMS_H_
#define TENMILMANUI_ENUMS_H_

namespace TenUI {	
	enum EXCEPTIONS { UIEXCEPTION_SDL_INIT_FAILED, UIEXCEPTION_OPENGL_INIT_FAILED };
	enum SCREEN_OPTION { FULLSCREEN, WINDOWED };
}

#endif /*TENMILMANUI_ENUMS_H_*/
